In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [6]:
c = np.array([[1, 2, 3],[4, 5, 6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [16]:
# Create Xeroes, Ones, custom array
a = np.zeros((3, 3))
print(a)
print("\n")

b = np.ones((2, 3))
print(b)
print("\n")

#Custom array
c = np.full((3, 2), 5)
print(c)
print("\n")

#Identity Matrix
d = np.eye(4)
print(d)
print("\n")

#Random Matrix
r = np.random.random((2, 3))
print(r)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[[5 5]
 [5 5]
 [5 5]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[0.8621673  0.54383857 0.32479945]
 [0.55291167 0.24953439 0.73989546]]


In [17]:
print(r[:,2])

[0.32479945 0.73989546]


In [18]:
r[1, 1:] = 1
print(r)

[[0.8621673  0.54383857 0.32479945]
 [0.55291167 1.         1.        ]]


In [25]:
## Set some rows and columns with any values
z = np.zeros((3, 3), dtype = np.int64)
print(z)
z[1,:] = 5
z[:, -1] = 7
print("\n")
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [26]:
# Datatypes
print(z.dtype)

int64


In [29]:
#Mathematical Operations

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x+y)
print("\n")
print(np.add(x, y))
print("\n")
print(x-y, "\n")
print(np.subtract(x, y))

[[ 6  8]
 [10 12]]


[[ 6  8]
 [10 12]]


[[-4 -4]
 [-4 -4]] 

[[-4 -4]
 [-4 -4]]


In [36]:
print(x*y, "\n")
print(np.multiply(x, y), "\n")
print(x/y, "\n")

[[ 5 12]
 [21 32]] 

[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 



In [33]:
# Matric Multiplication / dot Products
print(x, "\n")
print(y, "\n")
print(x.dot(y), "\n")
print(np.dot(x, y))

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]]


In [65]:
# Multiplication of Vectors - Dot Product - scalar
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])

print(a.dot(b))

30


In [37]:
print(a)

[1 2 3 4]


In [38]:
print(sum(a))

10


In [39]:
print(x)

[[1 2]
 [3 4]]


In [43]:
print(np.sum(x)) # Sum of all elements
print(np.sum(x, axis=0)) # Sum along colums
print(np.sum(x, axis=1)) # Sum along row

10
[4 6]
[3 7]


In [66]:
# Stack of arrays
print(a)
b = b+5
print(b)

[1 2 3 4]
[6 7 8 9]


In [57]:
np.stack((a, b), axis=1)


array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [67]:
a = np.stack((a, b), axis=0)

In [71]:
# Reshape a numpy array
#print(a, "\n")
a = a.reshape((4,-1))
print(a)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


# Random Module
- rand: Random Values in a given Space
- randn: Return a sample from the standard normal distribution
- randint: Return random integers from low to high
- random: Return random floats in the half-open interval [0.0, 2.0)
- choice: Generate a random sample from a given 1-D array
- Shuffle: Shuffles the content of a sequence

In [73]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [87]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[8 6 8]


In [81]:
a = np.random.randn(2, 3)
print(a)

a = np.random.randint(5, 10, 3)
print(a)

[[-0.09712492  1.23640723  0.45627915]
 [-0.06424569  0.65555143 -0.6216714 ]]
[8 6 8]


In [85]:
element = np.random.choice([10, 4, 5, 8, 9, 11])
print(element)

8


# Some More Numpy Functions - Statistics

- min, max
- mean
- median
- average
- variance
- standard deviation


In [90]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a, "\n")
print(np.min(a), "\n")
print(np.min(a, axis=0))
print(np.min(a, axis=1))

[[1 2 3 4]
 [7 6 2 0]] 

0 

[1 2 2 0]
[1 0]


In [92]:
print(np.mean(a))
print(np.mean(a, axis=0))

3.125
[4.  4.  2.5 2. ]


In [93]:
c = np.array([1, 5, 4, 2, 0])
print(np.median(c))

2.0


In [95]:
print(np.mean(c))

wts = np.array([1, 2, 3, 4, 5])
print(np.average(c, weights = wts))

2.4
2.066666666666667


In [100]:
u = np.mean(c)
my_std = np.sqrt(np.mean(abs(c-u)**2))
print(my_std)
print(np.std(c))

print(my_std**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
