In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.zeros(2)
print(b)

[0. 0.]


In [62]:
c = np.ones(2)
print(c)
c.dtype

[1. 1.]


dtype('float64')

In [8]:
d = np.empty(2)
print(d)

[1. 1.]


In [11]:
# Create an array with a range of elements.
e = np.arange(5)
print(e)

# Create an array with evenly spaced intervals. Specify Start Element, Last Element, Step Size.
f = np.arange(3, 8, 2)
print(f)

[0 1 2 3 4]
[3 5 7]


In [13]:
# Create array that is evenly spaced in a specified interval.
g = np.linspace(0, 12, num=5)
print(g)

[ 0.  3.  6.  9. 12.]


In [14]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

In [15]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.concatenate((e, f)) # e=[0, 1, 2, 3, 4] and f=[3, 5, 7]

array([0, 1, 2, 3, 4, 3, 5, 7])

In [24]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [0, 0, 0]])
#np.concatenate((x, y), axis=0)
np.concatenate((x, y), axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 0, 0]])

In [25]:
arr = np.array([[[0, 1, 2, 3],
...              [4, 5, 6, 7]],
...
...             [[0, 1, 2, 3],
...              [4, 5, 6, 7]],
...
...              [[0 ,1 ,2, 3],
...               [4, 5, 6, 7]]])

In [26]:
arr.ndim

3

In [27]:
arr.size

24

In [28]:
arr.shape

(3, 2, 4)

In [29]:
arr.reshape(1, 24)

array([[0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5,
        6, 7]])

In [33]:
b = np.arange(5)
b.shape

(5,)

In [38]:
row = b[np.newaxis,:]
row.shape

(1, 5)

In [40]:
data = np.arange(4)
data[1]

1

In [41]:
data[1:]

array([1, 2, 3])

In [42]:
data[0:2]

array([0, 1])

In [43]:
data[:-2]

array([0, 1])

In [44]:
data[-3:]

array([1, 2, 3])

In [47]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a>5])

[ 6  7  8  9 10 11 12]


In [52]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [53]:
d = c[2:5]
print(d)

[5 6 7]


In [55]:
c = d
np.vstack((c, d))

array([[5, 6, 7],
       [5, 6, 7]])

In [56]:
np.hstack((c, d))

array([5, 6, 7, 5, 6, 7])

In [60]:
x = np.array([[1, 2, 3],
             [3, 4, 5],
             [6, 7, 8]])

np.hsplit(x, (2,1))

[array([[1, 2],
        [3, 4],
        [6, 7]]),
 array([], shape=(3, 0), dtype=int32),
 array([[2, 3],
        [4, 5],
        [7, 8]])]

## Array Operations

In [63]:
data = np.arange(2)
one = np.ones(2, dtype=int)
data+one

array([1, 2])

In [65]:
data*data

array([0, 1])

In [66]:
data.sum()

1

In [67]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0) # Row sum

array([3, 3])

In [68]:
b.sum(axis=1) # Column Sum

array([2, 4])

In [73]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.max()

0.82485143

In [70]:
a.sum()

4.8595784

In [72]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [75]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))

[11 12 13 14 15 16 17 18 19 20]


In [77]:
unique_val, index = np.unique(a, return_index=True)
print(index)

[ 0  2  3  4  5  6  7 12 13 14]


In [78]:
unique_val, occ = np.unique(a, return_counts=True)
print(occ)

[3 2 2 2 1 1 1 1 1 1]


In [79]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.T

array([[0.45053314, 0.54627315, 0.12697628],
       [0.17296777, 0.05093587, 0.82485143],
       [0.34376245, 0.40067661, 0.26590556],
       [0.5510652 , 0.55645993, 0.56917101]])

In [80]:
np.flip(a)

array([[0.56917101, 0.26590556, 0.82485143, 0.12697628],
       [0.55645993, 0.40067661, 0.05093587, 0.54627315],
       [0.5510652 , 0.34376245, 0.17296777, 0.45053314]])

In [84]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.flip(a, axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [85]:
np.flip(a[:,1])

array([8, 5, 2])

In [87]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])